export let products = [
  {
    id: 1001,
    title: "Trufas de fresa",
    price: 65,
    stock: 1000,
    description:
      "Realizadas con leche condensada y chocolate blanco, el color se debe al uso de sirope de fresa y azúcar glas rosa.",
    category: "Trufas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585509/E-commerce%20ChocoLove/trufas-fresa_jvnq09.jpg",
  },
  {
    id: 1002,
    title: "Trufas de chocolate y vino",
    price: 70,
    stock: 1500,
    description:
      "Rellenas de chocolate y vino Cabernet Sauvignon, cubiertas de confite y cacao en polvo",
    category: "Trufas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585532/E-commerce%20ChocoLove/trufas-chocolate-vino_cjybgo.jpg",
  },
  {
    id: 1003,
    title: "Trufas de Chocolate Blanco y Coco",
    price: 60,
    stock: 800,
    description:
      "Rellenas de chocolate blanco, crema de leche y cocco, cubiertas de coco rallado",
    category: "Trufas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585529/E-commerce%20ChocoLove/trufa-chocolate-blanco-coco_x6txwe.jpg",
  },
  {
    id: 1004,
    title: "Trufas con bizcochuelo",
    price: 40,
    stock: 1100,
    description:
      "Rellenas de bizcochuelo y dulce de leche, cubiertas de coco rallado",
    category: "Trufas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585515/E-commerce%20ChocoLove/trufa-bizcochuelo_tvxyl8.jpg",
  },
  {
    id: 1005,
    title: "Bombones de tres chocolates",
    price: 50,
    stock: 1500,
    description:
      "Rellenos de chocolate blanco, cubiertos de chcolate negro, chocolate con leche y chocolate blanco",
    category: "Bombones",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585562/E-commerce%20ChocoLove/bombones-3-chocolates_vgtzfg.png",
  },
  {
    id: 1006,
    title: "Bombones de chocolate con mantequilla de maní",
    price: 75,
    stock: 1200,
    description:
      "Rellenos de chocolate blanco y mantequilla de maní, cubiertos de chocolate bitter",
    category: "Bombones",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585542/E-commerce%20ChocoLove/bombones-mantequilla-mani_ozj2ne.png",
  },
  {
    id: 1007,
    title: "Bombones de chocolate blanco rellenos de chocolate y almendras",
    price: 80,
    stock: 1000,
    description:
      "Relleno de chocolate con leche con almendras troceada y nocilla, cubiertos de chocolate blanco",
    category: "Bombones",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585558/E-commerce%20ChocoLove/bombones-blanco-almendras_wwvs70.png",
  },
  {
    id: 1010,
    title: "Bombones con frutos secos",
    price: 60,
    stock: 900,
    description: "Rellenos de frutos secos, cubiertos de chocolate negro",
    category: "Bombones",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1681585543/E-commerce%20ChocoLove/bombones-frutos-secos_k6sfe0.png",
  },
  {
    id: 1011,
    title: "Tableta de chocolate con relleno de dulce",
    price: 50,
    stock: 700,
    description:
      "Chocolate negro 70% cacao, rellenas de dulce de leche y nueces de macadamia",
    category: "Tabletas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1682203546/E-commerce%20ChocoLove/tableta-dulce-de-leche_df2gld.jpg",
  },
  {
    id: 1012,
    title: "Tableta con avellanas",
    price: 80,
    stock: 500,
    description: "Chocolate fondant, rellenas de avellanas y arándanos secos",
    category: "Tabletas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1682203550/E-commerce%20ChocoLove/tableta-avellanas_g6dkaw.jpg",
  },
  {
    id: 1013,
    title: "Tableta Kinder",
    price: 70,
    stock: 600,
    description:
      "Chocolate 80%, rellenas con leche. Mismo sabor al chocolate kinder, pero más saludable!",
    category: "Tabletas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1682203549/E-commerce%20ChocoLove/tableta-kinder_nawasd.jpg",
  },
  {
    id: 1014,
    title: "Tableta con Rocklets",
    price: 75,
    stock: 700,
    description: "Chocolate con leche, rellenas de Rocklets",
    category: "Tabletas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1682203550/E-commerce%20ChocoLove/tableta-rocklets_hutooc.jpg",
  },
  {
    id: 1015,
    title: "Tableta marmolada",
    price: 85,
    stock: 1000,
    description: "Chocolate blanco y negro con nueces",
    category: "Tabletas",
    img: "https://res.cloudinary.com/dhpyauyit/image/upload/v1682203551/E-commerce%20ChocoLove/tableta-marmolada_ejc3ai.jpg",
  },
];
